version: "2.1"
services:
  app:
    image: gbc
    depends_on:
      rabbitmq:
        condition: service_healthy
      database:
        condition: service_healthy
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
      - "9229:9229" # Debugger
    environment:
      - PORT=8087
      - TYPEORM_CONNECTION=mariadb
      - TYPEORM_HOST=localhost
      - TYPEORM_USERNAME=root
      - TYPEORM_PASSWORD= 
      - TYPEORM_DATABASE=bd_gbc
      - TYPEORM_PORT=3306
      - TYPEORM_SYNCHRONIZE=false
      - TYPEORM_LOGGING=false
      - TYPEORM_ENTITIES=src/models/*.ts
      - TYPEORM_MIGRATIONS=src/migrations/*.ts
      - TYPEORM_MIGRATIONS_DIR=src/migrations
    restart: on-failure
    working_dir: /usr/share/gbc
    volumes:
      - /usr/share/gbc/node_modules
      - ./src:/usr/share/gbc/src
    
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    restart: on-failure
    ports: 
      - "15672:15672"
    healthcheck:
      test:
        - "CMD"
        - "rabbitmqctl"
        - "status"
      interval: 10s
      timeout: 10s
      retries: 5

  database:
    image: mysql:5.6.44
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    healthcheck:
      test: "exit 0"
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  

